spring.application.name=neo4jfs
springdoc.api-docs.path=/swagger

neo4j.uri=bolt://localhost:7687
neo4j.username=neo4j
neo4j.password=Qwerty123!
neo4j.default.database=neo4j

neo4jfs.storage=local
neo4jfs.security=posix


logging.level.root=WARN
logging.level.dev.scottsosna.neo4jfs=DEBUG