# Neo4Jfs configuration properties, individual projects incorporating Neo4Jfs require these properties.
# Neo4J connection details
neo4j.uri=bolt://<neo4j_host>:<neo4j_bolt_port>>
neo4j.username=<neo4j_admin_user>
neo4j.password=<neo4j_admin_password>
neo4j.default.database=<neo4j_database_name>

# Neo4Jfs storage strategy.
neo4jfs.storage=local

# Logging configuration
logging.level.root=WARN
logging.level.dev.scottsosna.neo4jfs=INFO